import sys
import os
from pathlib import Path
import pandas as pd
import numpy as np
import pandas_ta_classic as ta
from dotenv import load_dotenv

# Add project root directory to sys.path
root_dir = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(root_dir))

# Import your working merger/fetchers
from data_pipeline.cleaning.merger import build_unified_dataset

# Load environment variables
load_dotenv(root_dir / '.env')

def engineer_features(ticker: str = "AAPL", start_date: str = "2023-01-01", end_date: str = "2026-08-01") -> pd.DataFrame:
    """Fetches merged data and calculates technical indicators via pandas-ta."""
    print(f"--- Building Feature Matrix for {ticker} ---")
    
    # 1. Fetch base unified dataset (Stock OHLCV + Macro VIX + Log Returns)
    df = build_unified_dataset(ticker=ticker, start_date=start_date, end_date=end_date)
    
    # Ensure dataframe is sorted by date ascending for sequential indicators
    df = df.sort_values('Date').reset_index(drop=True)
    
    # 2. Technical Indicators using pandas-ta
    # Relative Strength Index (RSI - 14 periods)
    df['RSI_14'] = ta.rsi(df['Close'], length=14)
    
    # Moving Average Convergence Divergence (MACD)
    macd_df = ta.macd(df['Close'], fast=12, slow=26, signal=9)
    # pandas-ta returns multiple columns; we join them safely
    if macd_df is not None and not macd_df.empty:
        df['MACD'] = macd_df.iloc[:, 0]       # MACD Line
        df['MACD_Signal'] = macd_df.iloc[:, 1] # Signal Line
        df['MACD_Hist'] = macd_df.iloc[:, 2]   # Histogram
        
    # Bollinger Bands (20 periods, 2 standard deviations)
    bb_df = ta.bbands(df['Close'], length=20, std=2)
    if bb_df is not None and not bb_df.empty:
        df['BB_Lower'] = bb_df.iloc[:, 0]
        df['BB_Middle'] = bb_df.iloc[:, 1]
        df['BB_Upper'] = bb_df.iloc[:, 2]
        
    # Simple Moving Average Ratio (SMA 20 vs SMA 50 trend confirmation)
    df['SMA_20'] = ta.sma(df['Close'], length=20)
    df['SMA_50'] = ta.sma(df['Close'], length=50)
    df['SMA_Ratio'] = df['SMA_20'] / df['SMA_50']
    
    # 3. Drop initial rows containing NaN values generated by technical window burn-in periods
    df.dropna(inplace=True)
    
    return df

if __name__ == "__main__":
    feature_df = engineer_features()
    print("\n--- Feature Engineering Complete ---")
    print(f"Total rows in feature matrix: {len(feature_df)}")
    print("\nSample Columns & Data:")
    print(feature_df[['Date', 'Close', 'RSI_14', 'MACD', 'SMA_Ratio', 'Target_Next_Return']].tail(3))
    
    # Optionally save to a CSV inside an outputs or data folder for modeling
    output_path = root_dir / 'ml' / 'datasets' / 'processed_features.csv'
    output_path.parent.mkdir(parents=True, exist_ok=True)
    feature_df.to_csv(output_path, index=False)
    print(f"\nSaved processed feature dataset to: {output_path}")